services:
  bdd:
    image: mariadb:11.7.2
    container_name: bdd-java
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: supermotdepasse
      MARIADB_DATABASE: live
    ports:
      - "3007:3006"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: