spring:
  application:
    name: live java web
  datasource:
    url: jdbc:mariadb://localhost:3307/live
    username: root
    password: supermotdepasse
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
